---
name: Build
on: [push, pull_request]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    uses: telia-company/casf-actions-workflows-shared-library/.github/workflows/python.yml@main
    with:
      version: "3.8"
